
###
GET {{host}}/users/all
Authorization: Bearer {{token}}

###
GET {{host}}/photos
Authorization: Bearer {{token}}


###
POST {{host}}/users/register
Content-Type: application/json

{
  "full_name": "sinaga",
  "email": "sinaga@gmail.com",
  "username": "sinaga",
  "password": "Diory123?",
  "profile_image_url": "https://res.cloudinary.com/dt3pzvmfg/image/upload/v1658573452/x1bbffnq1cold8srit8p.jpg",
  "age": 21,
  "phone_number":"081273232"
}

###
POST {{host}}/users/login
Content-Type: application/json

{
  "email": "sinaga@gmail.com",
  "password": "Diory123?"
}

###
PUT {{host}}/users/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "full_name": "Diory Pribadi Sinaga",
  "email": "diory2@gmail.com"
}

###
POST {{host}}/photos/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "poster_image_url": "https://res.cloudinary.com/dt3pzvmfg/image/upload/v1658573452/x1bbffnq1cold8srit8p.jpg",
  "title": "Photo sinaga 2",
  "caption": "Foto sinaga 2"
}

###
PUT {{host}}/photos/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Photo Keren"
}
###
DELETE {{host}}/users/3
Authorization: Bearer {{token}}

###
DELETE {{host}}/photos/1
Authorization: Bearer {{token}}

###
POST {{host}}/comments
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "comment": "Photonya keren",
  "PhotoId": 6
}
###
DELETE {{host}}/comments/5
Authorization: Bearer {{token}}

###
GET {{host}}/comments
Authorization: Bearer {{token}}
